### ISSUE TITLE
should be using bounds-of-thing-at-point

### ISSUE THREAD

**Issue by jgarvin** [akicho8/string-inflection#12]
Instead of doing your own forward scanning for words, you should be using the emacs concept of 'symbol'. What emacs calls a symbol basically corresponds to a variable name in all language modes. This has the advantage of behaving properly in all modes (for example string inflection does not work properly in emacs-lisp-mode) and even when using subword mode. It would also make string-inflection behave more consistently with other emacs commands. Currently if point is right after a symbol string-inflection will scan forward for the next word, but this is inconsistent with other emacs commands which would operate on the preceding word.

It would also simplify your code. Instead of trying to scan forward for a word, just call (bounds-of-thing-at-point 'symbol). If it can't find something just return an error.

**Comment by akicho8** [comment]
Thank you for teaching.
I did not know that there is (bounds-of-thing-at-point 'symbol).
In bounds-of-thing-at-point trial branch, use the bounds-of-thing-at-point.
Pick up the symbol code has become very simple.
https://github.com/akicho8/string-inflection/compare/bounds-of-thing-at-point

However, I string-inflection in emacs-lisp-mode is, does not work for the symbol, including the hyphen, so, do not think that's a problem.
Indeed, the behavior is changed automatically to it might be thought of Emacs by majar-mode.
I, in any majar-mode, I think to be the same behavior. Hyphen is desirably a boundary of symbol.

**Comment by wbolster** [comment]
perhaps this would help:

```elisp
(with-syntax-table TABLE &rest BODY)

Evaluate BODY with syntax table of current buffer set to TABLE.
The syntax table of the current buffer is saved, BODY is evaluated, and the
saved table is restored, even in case of an abnormal exit.
Value is what BODY returns.
```
