### ISSUE TITLE
Kebab case (hyphen-separated)

### ISSUE THREAD

**Issue by FrancescElies** [akicho8/string-inflection#14]
This is kind of a feature request,

I have been using this package and I am very happy with it 👍 
I would love to convert strings to kebab-case too
```
emacs_lisp => EMACS_LISP => EmacsLisp => emacsLisp => emacs_lisp => emacs-lisp
```

Would someone else also be interested in such a thing?
Would you well come a PR with such a feature?

All best & thanks

**Comment by akicho8** [comment]
In terms of `string-inflection-all-cycle`,
I think that the behavior of kebab-case is also good.

**Comment by akicho8** [comment]
@FrancescElies Support kebab-case.

https://github.com/akicho8/string-inflection/commit/4df4b62666991d6f57fe8968b20a8f938bade888#diff-aacb4ce123f9200898dff4a35e6a8461R50

**Comment by FrancescElies** [comment]
Awesome, just gave it a quick shot and seems to work fine!
