### ISSUE TITLE
cycling all does not wrap around?

### ISSUE THREAD

**Issue by wbolster** [akicho8/string-inflection#15]
first of all, awesome package. :)

repeatedly calling the `string-inflection-all-cycle` function seems not to wrap around. instead it stays stuck on `noInitialCamelCase` after cycling through a few variants first. i tried starting with `foo_bar`. am i missing something?

**Comment by akicho8** [comment]
@wbolster Thanks for the report.
Checking with emacs which has not set anything, it got the same state.
Fixed `string-inflection-camelcase-p`.
Please use 1.0.4.

https://github.com/akicho8/string-inflection/commit/d8766672af0d72aeb766f262d046377eed898253

**Comment by wbolster** [comment]
thanks!
