### ISSUE TITLE
Custom cycle

### ISSUE THREAD

**Issue by basille** [akicho8/string-inflection#20]
Not so much of an issue than a comment, or maybe a simple feature request…

I really like the idea and approach of `string-inflection`, it's really handy. Now, none of the proposed cycles (Ruby or Java) matches my own needs (which would be: foo_bar => fooBar => foo-bar => foo_bar). Following the source code for `string-inflection-XXX-style-cycle`, I ended up writing my own custom cycle function, bound to `C-c C-u`:

```
  (defun string-inflection-custom-cycle ()
    "foo_bar => fooBar => foo-bar => foo_bar"
    (interactive)
    (string-inflection-insert
     (string-inflection-custom-cycle-function (string-inflection-get-current-word))))

  (fset 'string-inflection-cycle 'string-inflection-custom-cycle)

  (defun string-inflection-custom-cycle-function (str)
    "foo_bar => fooBar => foo-bar => foo_bar"
    (cond
     ((string-inflection-underscore-p str)
      (string-inflection-lower-camelcase-function str))
     ((string-inflection-lower-camelcase-p str)
      (string-inflection-kebab-case-function str))
     (t
      (string-inflection-underscore-function str))))
```

Would it be possible to have a simpler mechanism to set our own custom cycles?

**Comment by akicho8** [comment]
Thank you for using. 😄 
Unfortunately we do not have a simple mechanism to set up our own custom cycle.
It is difficult to make it possible for the library to set in what order and how to convert.
If the prepared function does not meet the needs, there are some troublesome things, but as you wrote in the issue, I think that the way to define by oneself is simple, the effective and it is good.

**Comment by basille** [comment]
And it works perfectly for me! Hopefully it can be useful for other who'd like to have their own custom cycle.

(closing this issue, feel free to reopen if you ever want to implement it!)
