### ISSUE TITLE
Camel Case seems to be mislabeled.

### ISSUE THREAD

**Issue by jsmestad** [akicho8/string-inflection#25]
Looking through the docs it seems camel case and lower camel case are mislabeled.

> 
> Pascal case is a subset of Camel Case where the first letter is capitalized.
> 
> That is, userAccount is a camel case and UserAccount is a Pascal case.
> 
> The conventions of using these are different. You use camel case for variables and Pascal case for Class names or Constructors.
> 
> It is easy to remember. Pascal is a proper noun so capitalize the first letter.
> camel is a common noun, so you do not capitalize the first letter.

TL;DR

* `lower-camel-case` should be `camel-case`
* `camel-case` should be `pascal-case`

**Comment by akicho8** [comment]
Thank you for pointing out.

I saw the specification of ActiveSupport and thought that camelcase would be capitalized at the beginning.

```ruby
require "active_support/all"
"foo_bar".camelize              # => "FooBar"
"foo_bar".camelize(:lower)      # => "fooBar"
```

I looked at the Wikipedia and looked it on my own, but this seems to be incorrect.
Fix to properly use pascal-case and camelcase.

**Comment by jsmestad** [comment]
@akicho8 yeah I just recently found out what pascal case too 👍
