### ISSUE TITLE
Is there a way to make this work when the point is at the end of the string

### ISSUE THREAD

**Issue by it6** [akicho8/string-inflection#27]
When `point` is at the end of the word and I try to use `string-inflection` I get an `error code 2` message and the string doesn't change.

Is it possible to make it work when the `point` is at the end of the word, this is useful when typing in `mini buffer`

Once I start typing some word, If I want to change the case I have to go to the beginning of the word. Ideally I want to stay at the current position(which is end here) and still change the case.

**Comment by akicho8** [comment]
Thank you for using.

Even if there are points after the word, the word can be converted.

First enter a word. I will convert it in that state. Then the word to the left of the cursor will change.
For example, enter **foo**.
Then run `M-x string-inflection-all-cycle` or press the key to which it is assigned.
Then foo on the left side becomes **FOO**.

If there seems to be an error, please tell me the details of the error.

**Comment by it6** [comment]
I re-tested it and I still see an error

`string-inflection-all-cycle` works even when the point is after the word

but 

`string-inflection-kebab-case` works on the next word not the word behind it

**Comment by akicho8** [comment]
Thanks for the report.
I also tried it and recognized the problem.
