### ISSUE TITLE
Better Whitespace Handling When Converting a Region

### ISSUE THREAD

**Issue by sshaw** [akicho8/string-inflection#31]
Here I am calling `string-inflection-underscore` on the region:

![convert](https://user-images.githubusercontent.com/17570/124961263-3c7bff80-dfeb-11eb-85a4-4893d5ea5ac6.gif)

I would expect to get: 

```
    foo_bar
    foo_baz
```

**Comment by akicho8** [comment]
It seems that the behavior is different if it is my environment.
Why?

<img width="452" alt="スクリーンショット 2021-07-09 11 04 16" src="https://user-images.githubusercontent.com/808955/125012973-02236880-e0a6-11eb-943b-afc7b7204766.png">
<img width="464" alt="スクリーンショット 2021-07-09 11 08 06" src="https://user-images.githubusercontent.com/808955/125012977-03ed2c00-e0a6-11eb-9055-69cac4bd6409.png">

**Comment by sshaw** [comment]
> Why?

I see you're using Emacs 26.3. I'm using 27.1. Maybe this is why? 

Also using 20200927.747 from melpa which looks like it equals v1.0.12.

**Comment by akicho8** [comment]
I see.
I'll try after updating Emacs.

**Comment by akicho8** [comment]
After confirming with 27.2, it became the same way.

**Comment by akicho8** [comment]
Correction completed

**Comment by sshaw** [comment]
Yay, it's now working! 🎉 

Thanks.
