### ISSUE TITLE
kebabing a region can insert an unexpected `-`

### ISSUE THREAD

**Issue by vemv** [akicho8/string-inflection#34]
Hi again!

If I `M-x string-inflection-kebab-case` over:

```clj
:fooBar bar
```

I'll get:

```clj
-foo-bar bar
```

namely, I'll get an unexpected `-` prefix.

Does this sound familiar?

Thanks - V

**Comment by akicho8** [comment]
Hello!
It is better not to hyphen of the head.
After that I will make a modification.

**Comment by vemv** [comment]
Sweet! Thanks so much

**Comment by akicho8** [comment]
Correction is complete.

**Comment by vemv** [comment]
Mmm I tried it out and it doesn't appear to fully work for the following Clojure code:

```diff
-(s/def ::aA (s/coll-of ::aA))
-
-:aA
+(s-def -a-a (s-coll-of -a-a))
+
+a-a
```

**Comment by akicho8** [comment]
On the way `::aA` is not good to be `-a-a`
I will try to review a little more.

**Comment by akicho8** [comment]
Fixed again.
What about?

```diff
-(s/def ::aA (s/coll-of ::aA))
-
-:aA
+(s-def a-a (s-coll-of a-a))
+
+a-a
```

**Comment by akicho8** [comment]
> (note that in Clojure both `::foo` and `:foo` are valid)

I changed to not replace colons when selected.

**Comment by vemv** [comment]
Tested out. Works like a charm! Thanks so much for the sustained efforts.
