### ISSUE TITLE
Deletion of forward slashes?

### ISSUE THREAD

**Issue by E-A-Griffin** [akicho8/string-inflection#35]
I used `string-inflection-underscore` on some C code and it removed the forward slashes from the multi-line comments. Is this intentional?

**Comment by akicho8** [comment]
@E-A-Griffin 
It is the specification intended to remove the slash of the selected part in single line.
However, Honestly speaking, Processing for multi-line was unexpected.
Coincidentally, multi-line replace is worked.
I only use it to replace the keyword immediately entered.

for now, If change it as follows, Slash is not deleted.
`(setq string-inflection-erase-chars-when-region "./")`
↓
`(setq string-inflection-erase-chars-when-region ".")`
