### ISSUE TITLE
string-inflection doesn't work on words with umlauts

### ISSUE THREAD

**Issue by Kaligule** [akicho8/string-inflection#38]
(I love string-inflection, thanks a lot for it.)

To me it seems like there is an assumption baked into this package:
Words contain only ascii characters.
Therefore it breaks for words that have umlauts or similar in them:

- Käse
- KäsesoßenRührlöffel
- Löwenkäfig-Tür-Schließer

**Comment by akicho8** [comment]
Hello.
This feature targets keywords in source code written in commonly used alphabets.
We apologize, but it does not support special fonts.
