### ISSUE TITLE
Proposal to allow to maintain the cursor position after inflection

### ISSUE THREAD

**Issue by johannes-mueller** [akicho8/string-inflection#42]
So far, there is no option to maintain the cursor position where it was before the inflection. You can use `string-inflection-skip-backward-when-done` to determine if the cursor will end up at the end of the inflected string or jump to the beginning, but there is no option to make it remain where it was.

My proposal would be to replace `string-inflection-skip-backward-when-done` with a config variable `string-inflection-final-position` with the following semantics

* `'remain` → cursor remains where it was initially
* `'end` → cursor jumps to the end of the inflected string
* `'beginning` → cursor jumps to the beginning of the inflected string

Using `(bounds-of-symbol-at-point)` that would also allow us to drop `string-inflection-word-chars` and `string-inflection-non-word-chars`.

Please drop a short comment whether you are in favor of such a change. If yes I will implement it, if not I will set up a solution in my local config.

**Comment by akicho8** [comment]
I agree with the replacement of `string-inflection-final-position` and the use of `(bounds-of-symbol-at-point)`.
I will probably only use `'end`, but there will likely be others who prefer `'remain`.
