### ISSUE TITLE
A couple of ways to expand the packege

### ISSUE THREAD

**Issue by heikkil** [akicho8/string-inflection#7]
Thanks for the package! I was just thinking what would be the best way to do this when I saw the Emacs haiku in twitter.

I can see a couple of ways to make this package even more comprehensive while keeping it still focused on string infliction. At the moment the inflictions are all strictly related to changing variable names in various programming languages. There are at least two more general cases:
1. Handle dash (-) as a separator. 
2. Make it aware of the selection. If the selection contains space character(s) or any combination of space, dash or underscore [ _-], change them into underscore.

emacs lisp code -> emacs_lisp_code
emacs lisp-code -> emacs_lisp_code

It would be great if you could implement these features!

**Comment by hurtstotouchfire** [comment]
I'd like to implement `hyphen-case`. Is that something you're open to @akicho8? I would probably add another cycle to include it, so there's some discussion to be had as to what that should be called / should include.

**Comment by hurtstotouchfire** [comment]
Actually it looks like it's already in here as `'string-inflection-lisp`
https://github.com/akicho8/string-inflection/blob/master/string-inflection.el#L88

That toggles between `underscore_case` and `hyphen-case`. It could be better exposed though.
