### ISSUE TITLE
Please upload the packade to marmalade

### ISSUE THREAD

**Issue by the9000** [akicho8/string-inflection#8]
Could you please upload the packade to https://marmalade-repo.org/, or somewhere else, so that it could be more easily installed from within Emacs?

**Comment by akicho8** [comment]
I have been registered here
MELPA http://melpa.org/#/string-inflection

In this way, please try.

```lisp
(require 'package)

; Add package-archives
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))

; Initialize
(package-initialize)

; melpa.el
(require 'melpa)

```
M-x package-refresh-contents
M-x package-list-packages

**Comment by the9000** [comment]
Thank you, this worked nicely!
